/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  CostosArferts: () => import('#controllers/costos_arferts_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Precios: () => import('#controllers/precios_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
