/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CostosArfertSchema extends BaseModel {
  static $columns = ['caja', 'createdAt', 'envases', 'etiqueta', 'factor', 'flete', 'grupo', 'id', 'orden', 'producto', 'productoCosto', 'und', 'updatedAt'] as const
  $columns = CostosArfertSchema.$columns
  @column()
  declare caja: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare envases: string
  @column()
  declare etiqueta: string
  @column()
  declare factor: string
  @column()
  declare flete: string
  @column()
  declare grupo: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orden: number
  @column()
  declare producto: string
  @column()
  declare productoCosto: string
  @column()
  declare und: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductoSchema extends BaseModel {
  static $columns = ['createdAt', 'factor', 'grupo', 'id', 'orden', 'precio', 'producto', 'und', 'updatedAt', 'zonaId'] as const
  $columns = ProductoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare factor: string
  @column()
  declare grupo: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orden: number
  @column()
  declare precio: string
  @column()
  declare producto: string
  @column()
  declare und: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zonaId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ZonaSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nombre', 'updatedAt'] as const
  $columns = ZonaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
